const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const titles={chat:'與 Momo 對話',learn:'建立專屬知識',image:'本機圖像生成',speech:'離線語音工作室',weights:'觀察模型權重',mods:'擴充模組'};
let statusData=null;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});let data;try{data=await response.json()}catch{throw new Error(`HTTP ${response.status}`)}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function withButton(button,fn){const old=button.textContent;button.disabled=true;button.textContent='處理中…';try{return await fn()}catch(error){toast(error.message);throw error}finally{button.disabled=false;button.textContent=old}}
$$('#nav button').forEach(button=>button.onclick=()=>{$$('#nav button').forEach(x=>x.classList.toggle('active',x===button));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===button.dataset.panel));$('#pageTitle').textContent=titles[button.dataset.panel]});
$('#theme').onclick=()=>document.body.classList.toggle('light');
$('#chatInput').addEventListener('input',event=>{event.target.style.height='auto';event.target.style.height=Math.min(event.target.scrollHeight,180)+'px'});
$('#chatInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('#chatForm').requestSubmit()}});
function addMessage(role,text,meta=''){const article=document.createElement('article');article.className=`message ${role}`;const avatar=document.createElement('div');avatar.className='avatar';avatar.textContent=role==='momo'?'M':'Y';const box=document.createElement('div');const author=document.createElement('b');author.textContent=role==='momo'?'Momo':'You';const p=document.createElement('p');p.textContent=text;box.append(author,p);if(meta){const small=document.createElement('small');small.textContent=meta;box.append(small)}article.append(avatar,box);$('#messages').append(article);article.scrollIntoView({behavior:'smooth',block:'end'})}
$('#chatForm').onsubmit=async event=>{event.preventDefault();const input=$('#chatInput'),message=input.value.trim();if(!message)return;addMessage('user',message);input.value='';input.style.height='auto';const waiting=document.createElement('article');waiting.className='message momo';waiting.innerHTML='<div class="avatar">M</div><div><b>Momo</b><p>思考與檢索本機資料中…</p></div>';$('#messages').append(waiting);try{const result=await api('/api/chat',{method:'POST',body:JSON.stringify({message,learn:$('#learnToggle').checked})});waiting.remove();addMessage('momo',result.response,result.sources.length?`來源：${result.sources.join('、')}`:(result.learned?'已完成本機增量學習':''));await loadStatus()}catch(error){waiting.remove();addMessage('momo',`發生錯誤：${error.message}`)}};
$('#ingestBtn').onclick=()=>withButton($('#ingestBtn'),async()=>{const text=$('#learnText').value.trim();if(!text)throw new Error('請先輸入學習資料');const train=$('#trainNow').checked;const path=train?'/api/train':'/api/ingest';const body=train?{text,source:$('#source').value,epochs:Number($('#epochs').value)}:{text,source:$('#source').value,train:false};const result=await api(path,{method:'POST',body:JSON.stringify(body)});$('#learnResult').textContent=JSON.stringify(result,null,2);toast('資料已存入本機');await loadStatus()});
$('#crawlBtn').onclick=()=>withButton($('#crawlBtn'),async()=>{const result=await api('/api/crawl',{method:'POST',body:JSON.stringify({url:$('#crawlUrl').value,max_pages:Number($('#crawlPages').value),train:$('#crawlTrain').checked})});$('#learnResult').textContent=JSON.stringify(result,null,2);toast(`已處理 ${result.visited} 個頁面`);await loadStatus()});
$('#imageBtn').onclick=()=>withButton($('#imageBtn'),async()=>{const prompt=$('#imagePrompt').value.trim();if(!prompt)throw new Error('請輸入圖像描述');const size=Number($('#imageSize').value),seed=$('#imageSeed').value;const result=await api('/api/image',{method:'POST',body:JSON.stringify({prompt,width:size,height:size,seed})});const image=$('#imageOutput');image.src=result.url;image.classList.add('show');$('#imageEmpty').style.display='none';$('#downloadImage').href=result.url;$('#downloadImage').classList.add('show');toast('圖像已在本機生成')});
$('#speechRate').oninput=event=>$('#rateOutput').textContent=event.target.value;
$('#speechBtn').onclick=()=>withButton($('#speechBtn'),async()=>{const text=$('#speechText').value.trim();if(!text)throw new Error('請輸入要朗讀的文字');const result=await api('/api/tts',{method:'POST',body:JSON.stringify({text,rate:Number($('#speechRate').value)})});const audio=$('#audioOutput');audio.src=result.url;audio.classList.add('show');$('#speechEngine').textContent=`引擎：${result.engine}`;audio.play().catch(()=>{});toast('語音已產生')});
function n(value){return new Intl.NumberFormat().format(value)}
function renderStatus(data){statusData=data;$('#statusDot').classList.add('good');$('#statusText').textContent='本機模型已就緒';$('#modelMeta').textContent=`${n(data.weights.parameters)} parameters`;$('#learnToggle').checked=data.self_learning;$('#stats').innerHTML=`<div class="stat"><small>文字模型參數</small><strong>${n(data.weights.parameters)}</strong></div><div class="stat"><small>訓練步數</small><strong>${n(data.weights.training_steps)}</strong></div><div class="stat"><small>已學習 tokens</small><strong>${n(data.weights.tokens_seen)}</strong></div><div class="stat"><small>知識片段</small><strong>${n(data.knowledge.documents)}</strong></div>`;const max=Math.max(...Object.values(data.weights.layers).map(x=>x.parameters));$('#layers').innerHTML=Object.entries(data.weights.layers).map(([name,layer])=>`<div class="layer"><b>${name}</b><code>${layer.shape.join(' × ')}</code><div class="bar"><i style="width:${Math.max(2,layer.parameters/max*100)}%"></i></div><small>σ ${layer.std.toFixed(4)}</small></div>`).join('');renderMods(data.mods)}
function renderMods(mods){const items=mods.loaded.map(mod=>`<div class="mod"><b>${mod.name}</b> <small>v${mod.version}</small><p>${mod.description||'No description'}</p><code>${mod.commands.join(' · ')||'hooks only'}</code></div>`);const errors=mods.errors.map(x=>`<div class="mod"><b>載入失敗：${x.file}</b><p>${x.error}</p></div>`);$('#modList').innerHTML=[...items,...errors].join('')||'<div class="mod"><p>尚未載入模組。可從儲存庫的 mods/ 範例開始。</p></div>'}
async function loadStatus(){try{renderStatus(await api('/api/status'))}catch{$('#statusText').textContent='無法連接';$('#modelMeta').textContent='請檢查本機服務'}}
$('#refreshWeights').onclick=()=>loadStatus().then(()=>toast('權重狀態已更新'));
$('#reloadMods').onclick=()=>withButton($('#reloadMods'),async()=>{renderMods(await api('/api/mods/reload',{method:'POST',body:'{}'}));toast('Mods 已重新載入')});
loadStatus();
